"use client";

import { VisualDiffViewer } from "@admin/app/(main)/system/audit-logs/AuditLogsContent";
import { useRequirePermission } from "@admin/components/layout/PermissionGuard";
import { useToast } from "@admin/components/toast-provider";
import { ConfirmDialog } from "@admin/components/ui/ConfirmDialog";
import { useConfirm } from "@admin/components/ui/useConfirm";
import { trpc } from "@admin/lib/trpc";
import { formatDateTime } from "@admin/utils/dateFormat";
import type { ContentStatus } from "@flash-ship/ecom-types";

type RateCardType = "DEFAULT" | "CUSTOM";
type ShippingMethod = "EXPRESS" | "EPACKET";

import { Permissions } from "@flash-ship/ecom-lib/permissions";
import { Badge } from "@flash-ship/ecom-ui/components/badge";
import { Button } from "@flash-ship/ecom-ui/components/button";
import { Card, CardContent } from "@flash-ship/ecom-ui/components/card";
import { DatePicker } from "@flash-ship/ecom-ui/components/date-picker";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@flash-ship/ecom-ui/components/dialog";
import { Input } from "@flash-ship/ecom-ui/components/input";
import { Label } from "@flash-ship/ecom-ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@flash-ship/ecom-ui/components/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@flash-ship/ecom-ui/components/tabs";
import { cn } from "@flash-ship/ecom-ui/lib/utils";
import { zodResolver } from "@hookform/resolvers/zod";
import {
  AlertCircle,
  CheckCircle,
  ChevronLeft,
  History,
  Info,
  Loader2,
  Plus,
  Save,
  Scale,
  Trash2,
  UserPlus,
  Users,
  Wand2,
} from "lucide-react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useTranslations } from "next-intl";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type {
  Control,
  FieldErrors,
  UseFormRegister,
  UseFormSetValue,
  UseFormWatch,
} from "react-hook-form";
import { Controller, useForm } from "react-hook-form";
import { z } from "zod";

interface RateCardFormProps {
  rateCardId: number | null;
}

type SlabItem = {
  startWeight: number;
  endWeight: number;
  rateType: "STEP_FIXED" | "RANGE_FIXED" | "RANGE_PER_KG";
  amount: number;
  isAutoGenerated?: boolean;
  keyId: string;
};

function generateDefaultSlabs(
  minWeight: number,
  maxWeight: number,
  weightStep: number,
  rateType: SlabItem["rateType"] = "STEP_FIXED",
): SlabItem[] {
  if (minWeight == null || maxWeight == null || weightStep == null) return [];
  if (minWeight < 0 || maxWeight <= minWeight || weightStep <= 0) return [];
  const items: SlabItem[] = [];
  let curr = Number(Number(minWeight).toFixed(3));
  const maxW = Number(Number(maxWeight).toFixed(3));
  const step = Number(Number(weightStep).toFixed(3));

  while (curr < maxW) {
    let next = Number((curr + step).toFixed(3));
    if (next > maxW) next = maxW;
    items.push({
      startWeight: curr,
      endWeight: next,
      rateType,
      amount: 0,
      isAutoGenerated: true,
      keyId: `${curr}-${next}-${Math.random()}`,
    });
    curr = next;
  }
  return items;
}

const INITIAL_FORM_STATE = {
  code: "",
  name: "",
  type: "DEFAULT" as RateCardType,
  status: "DRAFT" as ContentStatus,
  shippingMethod: "EXPRESS" as ShippingMethod,
  country: "US",
  origin: "",
  currency: "USD",
  weightStep: 0.5,
  minWeight: 0.0,
  maxWeight: 10.0,
  startDate: "",
  endDate: "",
};

const rateCardFormSchema = z
  .object({
    code: z
      .string()
      .trim()
      .min(1, "rates.validationRequiredCode")
      .min(3, "rates.validationCodeMin")
      .max(100, "rates.validationCodeMax")
      .regex(/^[a-zA-Z0-9._-]+$/, "rates.validationCodeFormat"),
    name: z
      .string()
      .trim()
      .min(1, "rates.validationRequiredName")
      .min(3, "rates.validationNameMin")
      .max(200, "rates.validationNameMax"),
    type: z.custom<RateCardType>(),
    status: z.custom<ContentStatus>(),
    shippingMethod: z.custom<ShippingMethod>(),
    country: z.string(),
    origin: z.string(),
    currency: z.string(),
    weightStep: z
      .number({ message: "rates.validationRequiredWeightStep" })
      .positive("rates.validationWeightStep"),
    minWeight: z
      .number({ message: "rates.validationRequiredMinWeight" })
      .nonnegative("rates.validationMinWeight"),
    maxWeight: z
      .number({ message: "rates.validationRequiredMaxWeight" })
      .positive("rates.validationMaxWeight"),
    startDate: z
      .string()
      .trim()
      .min(1, "rates.validationRequiredStartDate")
      .refine(
        (val) => {
          if (!val) return false;
          const today = new Date();
          today.setHours(0, 0, 0, 0);
          const d = new Date(val);
          return d >= today;
        },
        { message: "rates.pastDateError" },
      ),
    endDate: z.string(),
  })
  .refine((data) => data.maxWeight > data.minWeight, {
    message: "rates.validationMaxWeight",
    path: ["maxWeight"],
  })
  .refine(
    (data) => {
      if (data.type === "DEFAULT") return true;
      if (!data.startDate || !data.endDate) return true;
      return new Date(data.startDate) <= new Date(data.endDate);
    },
    {
      message: "rates.validationDateRange",
      path: ["endDate"],
    },
  );

function formatErrorMessage(msg: string): string {
  if (!msg) return "";
  const parts = msg
    .split(/,\s*/)
    .map((p) => p.trim())
    .filter(Boolean);
  const uniqueParts = Array.from(new Set(parts));
  return uniqueParts.join(", ");
}

function mapExistingRateToForm(existingRate: {
  code?: string;
  name?: string;
  type?: string;
  status?: string;
  shippingMethod?: string;
  country?: string;
  origin?: string | null;
  currency?: string;
  weightStep?: unknown;
  minWeight?: unknown;
  maxWeight?: unknown;
  startDate?: Date | string | null;
  endDate?: Date | string | null;
}) {
  return {
    code: existingRate.code ?? "",
    name: existingRate.name ?? "",
    type: (existingRate.type ?? "DEFAULT") as RateCardType,
    status: (existingRate.status ?? "DRAFT") as ContentStatus,
    shippingMethod: (existingRate.shippingMethod ?? "EXPRESS") as ShippingMethod,
    country: existingRate.country ?? "US",
    origin: existingRate.origin ?? "",
    currency: existingRate.currency ?? "USD",
    weightStep: Number(existingRate.weightStep ?? 0.5),
    minWeight: Number(existingRate.minWeight ?? 0.0),
    maxWeight: Number(existingRate.maxWeight ?? 10.0),
    startDate: existingRate.startDate
      ? new Date(existingRate.startDate).toISOString().split("T")[0]
      : "",
    endDate: existingRate.endDate ? new Date(existingRate.endDate).toISOString().split("T")[0] : "",
  };
}

function mapExistingRateToSlabs(existingRate: {
  minWeight?: unknown;
  maxWeight?: unknown;
  weightStep?: unknown;
  items?: {
    startWeight?: unknown;
    endWeight?: unknown;
    rateType?: string;
    amount?: unknown;
  }[];
}): SlabItem[] {
  const minWeight = Number(existingRate.minWeight ?? 0);
  const maxWeight = Number(existingRate.maxWeight ?? 0);
  const weightStep = Number(existingRate.weightStep ?? 0.5);

  if (existingRate.items && existingRate.items.length > 0) {
    return existingRate.items.map((it) => {
      const sw = Number(it.startWeight ?? 0);
      const ew = Number(it.endWeight ?? 0);
      const isAutoGenerated = sw >= minWeight && ew <= maxWeight;

      return {
        startWeight: sw,
        endWeight: ew,
        rateType: (it.rateType ?? "STEP_FIXED") as SlabItem["rateType"],
        amount: Number(it.amount ?? 0),
        isAutoGenerated,
        keyId: `${sw}-${ew}-${Math.random()}`,
      };
    });
  }

  return generateDefaultSlabs(minWeight, maxWeight, weightStep);
}

function prepareSavePayload(formData: typeof INITIAL_FORM_STATE) {
  return {
    code: formData.code,
    name: formData.name,
    type: formData.type,
    shippingMethod: formData.shippingMethod,
    country: formData.country,
    origin: formData.origin.trim() === "" ? null : formData.origin.toUpperCase(),
    currency: formData.currency,
    weightStep: formData.weightStep,
    minWeight: formData.minWeight,
    maxWeight: formData.maxWeight,
    startDate: formData.startDate ? new Date(formData.startDate) : (undefined as unknown as Date),
    endDate:
      formData.type === "DEFAULT" ? null : formData.endDate ? new Date(formData.endDate) : null,
  };
}

interface StatusBadgeProps {
  status: string;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function StatusBadge({ status, tSettings }: StatusBadgeProps) {
  let variant: "default" | "secondary" | "destructive" | "outline" = "outline";
  let label: string = status;
  if (status === "PUBLISHED") {
    variant = "default";
    label = tSettings("rates.statusPublished");
  } else if (status === "DRAFT") {
    label = tSettings("rates.statusDraft");
  } else if (status === "PENDING") {
    variant = "secondary";
    label = tSettings("rates.statusPending");
  } else if (status === "REJECTED") {
    variant = "destructive";
    label = tSettings("rates.statusRejected");
  } else if (status === "ARCHIVED") {
    variant = "destructive";
    label = tSettings("rates.statusArchived");
  }
  return <Badge variant={variant}>{label}</Badge>;
}

function OverlapWarningBanner({
  cards,
}: {
  cards: Array<{ id?: number; code?: string; startDate?: string; endDate?: string }>;
}) {
  return (
    <div className="flex items-start gap-2.5 p-3 rounded-lg border border-amber-300 bg-amber-50 dark:bg-amber-950/30 text-amber-800 dark:text-amber-300 text-xs">
      <AlertCircle className="size-4 shrink-0 mt-0.5" />
      <div>
        <span className="font-semibold">Cảnh báo chồng chéo thời gian: </span>
        Khoảng thời gian hiệu lực này có nguy cơ xung đột với các bảng giá đang hoạt động:{" "}
        {cards
          .map((c) => c.code ?? "")
          .filter(Boolean)
          .join(", ")}
        .
      </div>
    </div>
  );
}

interface EffectiveDateFieldsProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  type: RateCardType;
  startDateStr?: string;
  isReadOnly: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  getErrorMessage: (field: keyof typeof INITIAL_FORM_STATE) => string | undefined;
}

function EffectiveDateFields({
  control,
  errors,
  type,
  startDateStr,
  isReadOnly,
  tSettings,
  getErrorMessage,
}: EffectiveDateFieldsProps) {
  const isPastDate = (date: Date) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return date < today;
  };

  const isInvalidEndDate = (date: Date) => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    if (date < today) return true;
    if (startDateStr) {
      const start = new Date(startDateStr);
      start.setHours(0, 0, 0, 0);
      if (date < start) return true;
    }
    return false;
  };

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">
          {tSettings("rates.lblStartDate")} <span className="text-destructive">*</span>
        </Label>
        <Controller
          control={control}
          name="startDate"
          render={({ field }) => (
            <DatePicker
              value={field.value ?? ""}
              onChange={field.onChange}
              placeholder="dd/mm/yyyy"
              disabled={isReadOnly}
              disabledDays={isPastDate}
            />
          )}
        />
        {errors.startDate && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("startDate")}
          </span>
        )}
      </div>
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">{tSettings("rates.lblEndDate")}</Label>
        {type === "DEFAULT" ? (
          <div className="h-9 px-3 border border-input rounded-md bg-muted/40 text-xs text-muted-foreground flex items-center">
            {tSettings("rates.defaultEndDateNote")}
          </div>
        ) : (
          <Controller
            control={control}
            name="endDate"
            render={({ field }) => (
              <DatePicker
                value={field.value ?? ""}
                onChange={field.onChange}
                placeholder="dd/mm/yyyy"
                disabled={isReadOnly}
                disabledDays={isInvalidEndDate}
              />
            )}
          />
        )}
        {errors.endDate && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("endDate")}
          </span>
        )}
      </div>
    </div>
  );
}

interface GeneralInfoTabProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  register: UseFormRegister<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  watch: UseFormWatch<typeof INITIAL_FORM_STATE>;
  setValue: UseFormSetValue<typeof INITIAL_FORM_STATE>;
  isCreate: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  status: ContentStatus;
  rateCardId: number | null;
  assignedGroups: { id: number; code: string; name: string }[];
  onOpenAssignGroups: () => void;
}

function getFieldErrorMessage(
  errors: FieldErrors<typeof INITIAL_FORM_STATE>,
  field: keyof typeof INITIAL_FORM_STATE,
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
) {
  const err = errors[field];
  if (!err?.message) return undefined;
  const msg = err.message as string;
  try {
    return tSettings(msg);
  } catch {
    return msg;
  }
}

interface WeightFieldsProps {
  control: Control<typeof INITIAL_FORM_STATE>;
  register: UseFormRegister<typeof INITIAL_FORM_STATE>;
  errors: FieldErrors<typeof INITIAL_FORM_STATE>;
  shippingMethod: ShippingMethod;
  isReadOnly: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  getErrorMessage: (field: keyof typeof INITIAL_FORM_STATE) => string | undefined;
}

function RateCardWeightFields({
  control,
  register,
  errors,
  shippingMethod,
  isReadOnly,
  tSettings,
  getErrorMessage,
}: WeightFieldsProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">
          {tSettings("rates.lblWeightStep")} <span className="text-destructive">*</span>
        </Label>
        <Controller
          control={control}
          name="weightStep"
          render={({ field }) => (
            <Select
              value={String(field.value)}
              disabled={isReadOnly}
              onValueChange={(v) => field.onChange(Number(v))}
            >
              <SelectTrigger
                className={errors.weightStep ? "border-destructive focus:ring-destructive" : ""}
              >
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {shippingMethod === "EPACKET" ? (
                  <>
                    <SelectItem value="0.05">0.05</SelectItem>
                    <SelectItem value="0.1">0.1</SelectItem>
                  </>
                ) : (
                  <>
                    <SelectItem value="0.5">0.5</SelectItem>
                    <SelectItem value="1">1.0</SelectItem>
                  </>
                )}
              </SelectContent>
            </Select>
          )}
        />
        {errors.weightStep && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("weightStep")}
          </span>
        )}
      </div>
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">
          {tSettings("rates.lblMinWeight")} <span className="text-destructive">*</span>
        </Label>
        <Input
          type="number"
          step={0.01}
          min={0}
          {...register("minWeight", { valueAsNumber: true })}
          disabled={isReadOnly}
          className={errors.minWeight ? "border-destructive focus-visible:ring-destructive" : ""}
        />
        {errors.minWeight && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("minWeight")}
          </span>
        )}
      </div>
      <div className="flex flex-col gap-1.5">
        <Label className="font-semibold text-xs">
          {tSettings("rates.lblMaxWeight")} <span className="text-destructive">*</span>
        </Label>
        <Input
          type="number"
          step={0.01}
          min={0}
          {...register("maxWeight", { valueAsNumber: true })}
          disabled={isReadOnly}
          className={errors.maxWeight ? "border-destructive focus-visible:ring-destructive" : ""}
        />
        {errors.maxWeight && (
          <span className="text-[11px] text-destructive font-medium mt-0.5">
            {getErrorMessage("maxWeight")}
          </span>
        )}
      </div>
    </div>
  );
}

function GeneralInfoTab({
  control,
  register,
  errors,
  watch,
  setValue,
  isCreate,
  tSettings,
  status,
  rateCardId,
  assignedGroups,
  onOpenAssignGroups,
}: GeneralInfoTabProps) {
  const shippingMethod = watch("shippingMethod");
  const type = watch("type");
  const country = watch("country");
  const origin = watch("origin");
  const startDateStr = watch("startDate");
  const endDateStr = watch("endDate");
  const isReadOnly = !isCreate && status !== "DRAFT" && status !== "REJECTED";

  const getErrorMessage = (field: keyof typeof INITIAL_FORM_STATE) =>
    getFieldErrorMessage(errors, field, tSettings);

  const { data: overlapRes } = trpc.viewer.rateCards.checkOverlap.useQuery(
    {
      excludeId: rateCardId ?? undefined,
      type,
      shippingMethod,
      country,
      origin: origin || undefined,
      startDate: startDateStr ? new Date(startDateStr) : undefined,
      endDate: endDateStr ? new Date(endDateStr) : undefined,
    },
    {
      enabled: !!shippingMethod && !!country && !!startDateStr,
      staleTime: 10 * 1000,
    },
  );

  return (
    <div className="flex flex-col gap-5">
      {overlapRes?.hasOverlap && overlapRes.overlappingCards && (
        <OverlapWarningBanner cards={overlapRes.overlappingCards} />
      )}

      {/* Customer Groups Callout for CUSTOM Rate Card */}
      {type === "CUSTOM" && !isCreate && (
        <div className="flex flex-col gap-2 rounded-lg border border-border bg-muted/20 p-4">
          <div className="flex items-center justify-between gap-2">
            <Label className="font-semibold text-xs flex items-center gap-1.5">
              <Users className="size-4 text-primary" />
              Nhóm khách hàng áp dụng <span className="text-destructive">*</span>
            </Label>
            {!isReadOnly && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                className="h-8 text-xs gap-1"
                onClick={onOpenAssignGroups}
              >
                <UserPlus className="size-3.5" />
                {assignedGroups.length > 0 ? "Chỉnh sửa nhóm" : "Gán nhóm khách hàng"}
              </Button>
            )}
          </div>

          {assignedGroups.length > 0 ? (
            <div className="flex flex-wrap gap-1.5 pt-1">
              {assignedGroups.map((g) => (
                <Badge key={g.id} variant="secondary" className="text-xs">
                  {g.name} ({g.code})
                </Badge>
              ))}
            </div>
          ) : (
            <div className="flex items-center gap-2 rounded-md border border-amber-300 bg-amber-50 px-3 py-2 text-xs text-amber-800 dark:bg-amber-950/30 dark:text-amber-300">
              <AlertCircle className="size-4 shrink-0" />
              <span>
                <strong>Chưa gán nhóm khách hàng:</strong> Bảng giá tùy chỉnh bắt buộc phải được gán
                ít nhất một nhóm khách hàng trước khi gửi duyệt.
              </span>
            </div>
          )}
        </div>
      )}

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="code" className="font-semibold text-xs">
            {tSettings("rates.lblCode")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="code"
            {...register("code")}
            maxLength={100}
            placeholder={tSettings("rates.placeholderCode")}
            disabled={isReadOnly}
            className={errors.code ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.code && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("code")}
            </span>
          )}
        </div>
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="name" className="font-semibold text-xs">
            {tSettings("rates.lblName")} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="name"
            {...register("name")}
            maxLength={200}
            placeholder={tSettings("rates.placeholderName")}
            disabled={isReadOnly}
            className={errors.name ? "border-destructive focus-visible:ring-destructive" : ""}
          />
          {errors.name && (
            <span className="text-[11px] text-destructive font-medium mt-0.5">
              {getErrorMessage("name")}
            </span>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblType")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="type"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isReadOnly}
                onValueChange={(v) => {
                  field.onChange(v);
                  if (v === "DEFAULT") {
                    setValue("endDate", "", { shouldDirty: true, shouldValidate: true });
                  }
                }}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="DEFAULT">{tSettings("rates.typeDefault")}</SelectItem>
                  <SelectItem value="CUSTOM">{tSettings("rates.typeCustom")}</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>

        <div className="flex flex-col gap-1.5">
          <Label className="font-semibold text-xs">
            {tSettings("rates.lblShippingMethod")} <span className="text-destructive">*</span>
          </Label>
          <Controller
            control={control}
            name="shippingMethod"
            render={({ field }) => (
              <Select
                value={field.value}
                disabled={isReadOnly}
                onValueChange={(v) => {
                  field.onChange(v);
                  const defaultStep = v === "EPACKET" ? 0.05 : 0.5;
                  setValue("weightStep", defaultStep, { shouldDirty: true, shouldValidate: true });
                }}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="EXPRESS">Express</SelectItem>
                  <SelectItem value="EPACKET">ePacket</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
        </div>
      </div>

      <RateCardWeightFields
        control={control}
        register={register}
        errors={errors}
        shippingMethod={shippingMethod}
        isReadOnly={isReadOnly}
        tSettings={tSettings}
        getErrorMessage={getErrorMessage}
      />

      <EffectiveDateFields
        control={control}
        errors={errors}
        type={type}
        startDateStr={startDateStr}
        isReadOnly={isReadOnly}
        tSettings={tSettings}
        getErrorMessage={getErrorMessage}
      />
    </div>
  );
}

interface SlabsTabProps {
  formData: {
    code: string;
    currency: string;
    minWeight: number;
    maxWeight: number;
    weightStep: number;
    status: ContentStatus;
  };
  slabs: SlabItem[];
  setSlabs: React.Dispatch<React.SetStateAction<SlabItem[]>>;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  isReadOnly?: boolean;
  askConfirm: (options: {
    title?: string;
    message: string;
    confirmLabel?: string;
    cancelLabel?: string;
    confirmColor?: "error" | "primary" | "warning";
    onConfirm: () => void;
  }) => void;
}

function getSlabMinCost(slab: SlabItem): number {
  if (slab.rateType === "RANGE_PER_KG") {
    return slab.startWeight * slab.amount;
  }
  return slab.amount;
}

function getSlabMaxCost(slab: SlabItem): number {
  if (slab.rateType === "RANGE_PER_KG") {
    return slab.endWeight * slab.amount;
  }
  return slab.amount;
}

function validateSlabRow(
  curr: SlabItem,
  prev: SlabItem | undefined,
  index: number,
  _totalSlabs: number,
  formData: { minWeight: number; maxWeight: number },
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
) {
  if (curr.startWeight < 0) {
    return {
      startWeight: true,
      reason: tSettings("rates.errStartWeightNegative"),
    };
  }

  if (curr.endWeight < 0) {
    return {
      endWeight: true,
      reason: tSettings("rates.errEndWeightNegative"),
    };
  }

  if (curr.amount < 0) {
    return {
      amount: true,
      reason: tSettings("rates.errAmountNegative"),
    };
  }

  if (curr.startWeight >= curr.endWeight) {
    return {
      startWeight: true,
      endWeight: true,
      reason: tSettings("rates.errWeightBounds"),
    };
  }

  const isFirstMinMismatch =
    index === 0 && formData.minWeight != null && curr.startWeight !== formData.minWeight;
  const isGap = prev ? curr.startWeight !== prev.endWeight : false;
  const isMonotonic = prev ? getSlabMinCost(curr) < getSlabMaxCost(prev) : false;

  if (!isFirstMinMismatch && !isGap && !isMonotonic) {
    return {};
  }

  const reason = isFirstMinMismatch
    ? tSettings("rates.errMinWeightMismatch", {
        minWeight: formData.minWeight,
        current: curr.startWeight,
      })
    : isGap
      ? tSettings("rates.errGap", { prevEnd: prev?.endWeight ?? 0 })
      : tSettings("rates.errMonotonicity");

  return {
    startWeight: isFirstMinMismatch || isGap,
    endWeight: false,
    amount: isMonotonic,
    reason,
  };
}

function countSlabErrors(
  slabs: SlabItem[],
  formData: { minWeight: number; maxWeight: number },
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string,
): number {
  let errCount = 0;
  for (let i = 0; i < slabs.length; i++) {
    const err = validateSlabRow(slabs[i], slabs[i - 1], i, slabs.length, formData, tSettings);
    if (err.startWeight || err.endWeight || err.amount) errCount++;
  }
  return errCount;
}

function SlabsTab({
  formData,
  slabs,
  setSlabs,
  tSettings,
  isReadOnly = false,
  askConfirm,
}: SlabsTabProps) {
  const t = useToast();
  const hasAutoGeneratedRef = useRef(false);

  const templateQuery = trpc.viewer.rateCards.exportSlabsTemplate.useQuery(
    {
      minWeight: formData.minWeight,
      maxWeight: formData.maxWeight,
      weightStep: formData.weightStep,
      rateType: "STEP_FIXED",
    },
    { enabled: false },
  );

  useEffect(() => {
    if (
      !isReadOnly &&
      slabs.length === 0 &&
      !hasAutoGeneratedRef.current &&
      formData.minWeight != null &&
      formData.maxWeight != null &&
      formData.weightStep > 0
    ) {
      const generated = generateDefaultSlabs(
        formData.minWeight,
        formData.maxWeight,
        formData.weightStep,
      );
      if (generated.length > 0) {
        hasAutoGeneratedRef.current = true;
        setSlabs(generated);
      }
    }
  }, [
    isReadOnly,
    slabs.length,
    formData.minWeight,
    formData.maxWeight,
    formData.weightStep,
    setSlabs,
  ]);

  const handleAutoGenerateSlabs = async () => {
    if (isReadOnly) return;
    if (!formData.minWeight && formData.minWeight !== 0) {
      t.toast(tSettings("rates.toastAutoGenerateError"), "error");
      return;
    }

    const doGenerate = async () => {
      const res = await templateQuery.refetch();
      if (res.data?.slabs) {
        const generated: SlabItem[] = res.data.slabs.map((s) => ({
          ...s,
          isAutoGenerated: true,
          keyId: `${s.startWeight}-${s.endWeight}-${Math.random()}`,
        }));
        setSlabs(generated);
      }
    };

    const hasFilledData = slabs.some((s) => s.amount > 0);
    if (slabs.length > 0 && hasFilledData) {
      askConfirm({
        title: "Xác nhận tạo tự động lại nấc cước",
        message: `Bạn có chắc chắn muốn tạo tự động lại danh sách nấc cước theo nấc ${formData.weightStep}kg (từ ${formData.minWeight}kg đến ${formData.maxWeight}kg) không?\n\nLưu ý: Toàn bộ danh sách nấc cước và giá cước hiện tại sẽ bị ghi đè.`,
        confirmLabel: "Sinh lại nấc cước",
        cancelLabel: "Hủy",
        confirmColor: "warning",
        onConfirm: () => {
          void doGenerate();
        },
      });
    } else {
      await doGenerate();
    }
  };

  const handleAddSlabRow = () => {
    if (isReadOnly) return;
    const last = slabs[slabs.length - 1];
    const start = last ? last.endWeight : formData.minWeight;
    const end = start + (formData.weightStep || 0.5);
    setSlabs((prev) => [
      ...prev,
      {
        startWeight: start,
        endWeight: end,
        rateType: "STEP_FIXED",
        amount: 0.0,
        isAutoGenerated: false,
        keyId: `${start}-${end}-${Math.random()}`,
      },
    ]);
  };

  const handleRemoveSlabRow = (index: number) => {
    if (isReadOnly) return;
    const target = slabs[index];
    if (!target) return;

    const prevSlab = slabs[index - 1];
    const nextSlab = slabs[index + 1];

    let changeExplanation = "";
    if (prevSlab && nextSlab) {
      changeExplanation = `Nấc cước liền trước [${prevSlab.startWeight} -> ${prevSlab.endWeight}kg] sẽ được tự động mở rộng thành [${prevSlab.startWeight} -> ${target.endWeight}kg] để nối liền khoảng cân.`;
    } else if (!prevSlab && nextSlab) {
      changeExplanation = `Nấc cước kế tiếp [${nextSlab.startWeight} -> ${nextSlab.endWeight}kg] sẽ tự động điều chỉnh bắt đầu từ ${target.startWeight}kg ([${target.startWeight} -> ${nextSlab.endWeight}kg]).`;
    } else {
      changeExplanation = "Nấc cước cuối cùng sẽ được gỡ bỏ khỏi bảng giá.";
    }

    askConfirm({
      title: "Xác nhận xóa nấc cước",
      message: `Bạn có chắc chắn muốn xóa nấc cước [${target.startWeight} -> ${target.endWeight}kg] không?\n\n${changeExplanation}`,
      confirmLabel: "Xóa nấc cước",
      cancelLabel: "Hủy",
      confirmColor: "error",
      onConfirm: () => {
        setSlabs((prev) => {
          if (prev.length <= 1) return [];
          const curTarget = prev[index];
          const curPrev = prev[index - 1];
          const curNext = prev[index + 1];

          const nextList = prev.filter((_, i) => i !== index);

          if (curPrev && curNext && curTarget) {
            const prevIndexInNext = index - 1;
            nextList[prevIndexInNext] = {
              ...nextList[prevIndexInNext],
              endWeight: curTarget.endWeight,
            };
          } else if (!curPrev && curNext && curTarget) {
            nextList[0] = {
              ...nextList[0],
              startWeight: curTarget.startWeight,
            };
          }

          return nextList;
        });
      },
    });
  };

  const updateSlabField = (index: number, field: keyof SlabItem, value: unknown) => {
    if (isReadOnly) return;
    setSlabs((prev) =>
      prev.map((s, i) => {
        if (i === index) {
          return { ...s, [field]: value };
        }
        return s;
      }),
    );
  };

  const slabErrors = useMemo(() => {
    const errMap: Record<
      number,
      { startWeight?: boolean; endWeight?: boolean; amount?: boolean; reason?: string }
    > = {};

    for (let i = 0; i < slabs.length; i++) {
      const err = validateSlabRow(slabs[i], slabs[i - 1], i, slabs.length, formData, tSettings);
      if (err.startWeight || err.endWeight || err.amount) {
        errMap[i] = err;
      }
    }

    return errMap;
  }, [slabs, formData, tSettings]);

  const hasMonotonicityWarning = useMemo(() => {
    return Object.values(slabErrors).some((e) => e.amount);
  }, [slabErrors]);

  return (
    <div className="flex flex-col gap-4">
      {isReadOnly && (
        <div className="bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-900 rounded-md p-3 text-xs text-blue-800 dark:text-blue-200 flex items-center gap-2">
          <Info className="size-4 shrink-0 text-blue-600 dark:text-blue-400" />
          <span>
            Bảng giá ở trạng thái <strong>{formData.status}</strong> đã được khóa nấc cước để đảm
            bảo tính toàn vẹn dữ liệu tính cước đơn hàng.
          </span>
        </div>
      )}

      {hasMonotonicityWarning && (
        <div className="bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-900 rounded-md p-3 text-xs text-amber-800 dark:text-amber-200 flex items-start gap-2">
          <AlertCircle className="size-4 shrink-0 text-amber-600 mt-0.5" />
          <div>
            <strong>{tSettings("rates.warningLabel")}</strong>{" "}
            {tSettings("rates.warningMonotonicity")}
          </div>
        </div>
      )}

      {!isReadOnly && (
        <div className="flex flex-wrap items-center justify-between gap-3 bg-muted/20 p-3 rounded-lg border border-border">
          <Button size="sm" variant="outline" className="h-8" onClick={handleAutoGenerateSlabs}>
            <Wand2 className="mr-1.5 size-3.5" />
            {tSettings("rates.btnAutoGenerate")}
          </Button>
        </div>
      )}

      <div className="border border-border rounded-lg overflow-hidden">
        <table className="w-full text-xs text-left">
          <thead className="bg-muted/50 border-b border-border text-muted-foreground font-semibold">
            <tr>
              <th className="px-3 py-2">{tSettings("rates.colStart")}</th>
              <th className="px-3 py-2">{tSettings("rates.colEnd")}</th>
              <th className="px-3 py-2">{tSettings("rates.colSlabType")}</th>
              <th className="px-3 py-2">
                {tSettings("rates.colAmount", { currency: formData.currency })}
              </th>
              {!isReadOnly && (
                <th className="px-3 py-2 text-center w-20 whitespace-nowrap">
                  {tSettings("rates.colDelete")}
                </th>
              )}
            </tr>
          </thead>
          <tbody className="divide-y divide-border">
            {slabs.map((slab, index) => {
              const err = slabErrors[index];
              return (
                <tr
                  key={slab.keyId ?? index}
                  className={cn("hover:bg-muted/20", err && "bg-destructive/5")}
                >
                  <td className="px-3 py-1.5 align-top">
                    <Input
                      type="number"
                      step={0.01}
                      min={0}
                      value={slab.startWeight}
                      onChange={(e) =>
                        updateSlabField(index, "startWeight", Number(e.target.value))
                      }
                      disabled={isReadOnly || slab.isAutoGenerated}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.startWeight &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                    {err?.startWeight && err?.reason && (
                      <span className="text-[10px] text-destructive block mt-0.5 font-medium">
                        {err.reason}
                      </span>
                    )}
                  </td>
                  <td className="px-3 py-1.5 align-top">
                    <Input
                      type="number"
                      step={0.01}
                      min={0}
                      value={slab.endWeight}
                      onChange={(e) => updateSlabField(index, "endWeight", Number(e.target.value))}
                      disabled={isReadOnly || slab.isAutoGenerated}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.endWeight &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                    {err?.endWeight && !err?.startWeight && err?.reason && (
                      <span className="text-[10px] text-destructive block mt-0.5 font-medium">
                        {err.reason}
                      </span>
                    )}
                  </td>
                  <td className="px-3 py-1.5 align-top">
                    <Select
                      value={slab.rateType}
                      onValueChange={(v) =>
                        updateSlabField(index, "rateType", v as SlabItem["rateType"])
                      }
                      disabled={isReadOnly || slab.isAutoGenerated}
                    >
                      <SelectTrigger className="h-7 text-xs px-2">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="STEP_FIXED">
                          {tSettings("rates.typeStepFixed")}
                        </SelectItem>
                        <SelectItem value="RANGE_FIXED">
                          {tSettings("rates.typeRangeFixed")}
                        </SelectItem>
                        <SelectItem value="RANGE_PER_KG">
                          {tSettings("rates.typeRangePerKg")}
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </td>
                  <td className="px-3 py-1.5 align-top">
                    <Input
                      id={`slab-amount-input-${index}`}
                      type="number"
                      step={0.01}
                      min={0}
                      value={slab.amount}
                      onChange={(e) => updateSlabField(index, "amount", Number(e.target.value))}
                      onKeyDown={(e) => {
                        if (e.key === "Enter" || e.key === "ArrowDown") {
                          e.preventDefault();
                          const nextInput = document.getElementById(
                            `slab-amount-input-${index + 1}`,
                          ) as HTMLInputElement | null;
                          if (nextInput) {
                            nextInput.focus();
                            nextInput.select();
                          }
                        } else if (e.key === "ArrowUp") {
                          e.preventDefault();
                          const prevInput = document.getElementById(
                            `slab-amount-input-${index - 1}`,
                          ) as HTMLInputElement | null;
                          if (prevInput) {
                            prevInput.focus();
                            prevInput.select();
                          }
                        }
                      }}
                      onFocus={(e) => {
                        e.target.select();
                      }}
                      disabled={isReadOnly}
                      className={cn(
                        "h-7 text-xs px-2",
                        err?.amount &&
                          "border-destructive text-destructive bg-destructive/10 focus-visible:ring-destructive font-medium",
                      )}
                    />
                    {err?.amount && err?.reason && (
                      <span className="text-[10px] text-destructive block mt-0.5 font-medium">
                        {err.reason}
                      </span>
                    )}
                    {!err?.startWeight && !err?.endWeight && !err?.amount && err?.reason && (
                      <span className="text-[10px] text-destructive block mt-0.5 font-medium">
                        {err.reason}
                      </span>
                    )}
                  </td>
                  {!isReadOnly && (
                    <td className="px-3 py-1.5 text-center">
                      <Button
                        size="icon"
                        variant="ghost"
                        className="size-7 text-destructive"
                        onClick={() => handleRemoveSlabRow(index)}
                      >
                        <Trash2 className="size-3.5" />
                      </Button>
                    </td>
                  )}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {!isReadOnly && (
        <Button size="sm" variant="outline" className="w-fit" onClick={handleAddSlabRow}>
          <Plus className="mr-1.5 size-3.5" />
          {tSettings("rates.btnAddSlab")}
        </Button>
      )}
    </div>
  );
}

interface LogsTabProps {
  logs?: {
    id?: number;
    action?: string;
    createdAt?: Date | string;
    userId?: string;
    user?: { name: string; id: string; email: string } | null;
    oldValues?: unknown;
    newValues?: unknown;
  }[];
  loadingLogs: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
}

function LogsTab({ logs, loadingLogs, tSettings }: LogsTabProps) {
  const tAudit = useTranslations("auditLogs");

  return (
    <div className="flex flex-col gap-4">
      {loadingLogs ? (
        <div className="flex py-12 justify-center items-center">
          <Loader2 className="size-6 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <div className="relative border-l border-border ml-3 pl-5 space-y-4">
          {logs?.map((log, index) => {
            return (
              <div key={log.id ?? index} className="relative group text-xs">
                <div className="absolute -left-[26px] top-0.5 size-3 rounded-full border-2 border-background bg-primary group-hover:scale-110 transition-transform" />

                <div className="flex justify-between text-muted-foreground mb-1">
                  <span className="font-semibold text-foreground">{log.action ?? ""}</span>
                  <span>
                    {log.createdAt ? formatDateTime(log.createdAt, "DD-MM-YYYY HH:mm:ss") : ""}
                  </span>
                </div>

                <div className="bg-muted/40 border border-border/60 rounded-md p-4 space-y-3">
                  <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground border-b border-border/40 pb-2">
                    <Users className="size-3.5" />
                    <span>
                      {tSettings("rates.logPerformedBy")}{" "}
                      <strong className="text-foreground">
                        {log.user?.email || tSettings("rates.logSystem")}
                      </strong>
                    </span>
                  </div>

                  <VisualDiffViewer
                    action={log.action}
                    oldValues={log.oldValues}
                    newValues={log.newValues}
                    t={tAudit}
                  />
                </div>
              </div>
            );
          })}

          {(!logs || logs.length === 0) && (
            <div className="text-center py-6 text-muted-foreground italic text-xs">
              {tSettings("rates.noLogsFound")}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

interface FormHeaderProps {
  isCreate: boolean;
  code: string;
  status: string;
  activeTab: "info" | "slabs" | "logs";
  isPending: boolean;
  slabsCount: number;
  totalSlabErrors?: number;
  hasAssignedGroups?: boolean;
  tSettings: (key: string, values?: Record<string, string | number | Date>) => string;
  onBack: () => void;
  onSaveInfo: () => void;
  onSubmitReview?: () => void;
  onApprove?: () => void;
  onReject?: () => void;
  onSaveSlabs: () => void;
  isInfoDirty?: boolean;
  isSlabsDirty?: boolean;
  isReadOnly?: boolean;
  canCreate?: boolean;
  canUpdate?: boolean;
  canApprove?: boolean;
}

function SaveButton({
  isPending,
  code,
  isCreate,
  isInfoDirty,
  tSettings,
  onSaveInfo,
}: {
  isPending: boolean;
  code: string;
  isCreate: boolean;
  isInfoDirty?: boolean;
  tSettings: (key: string) => string;
  onSaveInfo: () => void;
}) {
  return (
    <Button
      size="sm"
      variant="outline"
      disabled={isPending || !code || (!isCreate && !isInfoDirty)}
      onClick={onSaveInfo}
    >
      {isPending ? (
        <Loader2 className="mr-2 size-4 animate-spin" />
      ) : (
        <Save className="mr-2 size-4" />
      )}
      {isCreate ? tSettings("rates.btnCreate") : tSettings("rates.btnSave")}
    </Button>
  );
}

function ApprovalButtons({
  isPending,
  totalSlabErrors,
  onApprove,
  onReject,
  tSettings,
}: {
  isPending: boolean;
  totalSlabErrors: number;
  onApprove?: () => void;
  onReject?: () => void;
  tSettings: (key: string) => string;
}) {
  return (
    <>
      {onReject && (
        <Button size="sm" variant="destructive" disabled={isPending} onClick={onReject}>
          {tSettings("rates.btnReject")}
        </Button>
      )}
      {onApprove && (
        <Button size="sm" disabled={isPending || totalSlabErrors > 0} onClick={onApprove}>
          <CheckCircle className="mr-2 size-4" />
          {tSettings("rates.btnApprove")}
        </Button>
      )}
    </>
  );
}

function InfoTabButtons({
  isCreate,
  status,
  code,
  isPending,
  isInfoDirty,
  totalSlabErrors = 0,
  hasAssignedGroups = true,
  tSettings,
  onSaveInfo,
  onSubmitReview,
  onApprove,
  onReject,
  canCreate = true,
  canUpdate = true,
  canApprove = true,
}: Omit<FormHeaderProps, "activeTab" | "slabsCount" | "onBack" | "onSaveSlabs" | "isSlabsDirty">) {
  const isDraftOrRejected = status === "DRAFT" || status === "REJECTED";
  const canSave = isCreate ? canCreate : canUpdate && isDraftOrRejected;
  const canSubmit = !isCreate && canUpdate && isDraftOrRejected && hasAssignedGroups;
  const canApproveReject = !isCreate && canApprove && status === "PENDING";

  return (
    <>
      {canSave && (
        <SaveButton
          isPending={isPending}
          code={code}
          isCreate={isCreate}
          isInfoDirty={isInfoDirty}
          tSettings={tSettings}
          onSaveInfo={onSaveInfo}
        />
      )}

      {canSubmit && onSubmitReview && (
        <Button size="sm" disabled={isPending || totalSlabErrors > 0} onClick={onSubmitReview}>
          <CheckCircle className="mr-2 size-4" />
          {tSettings("rates.btnSubmitReview")}
        </Button>
      )}

      {canApproveReject && (
        <ApprovalButtons
          isPending={isPending}
          totalSlabErrors={totalSlabErrors}
          onApprove={onApprove}
          onReject={onReject}
          tSettings={tSettings}
        />
      )}
    </>
  );
}

function FormHeader(props: FormHeaderProps) {
  const {
    isCreate,
    code,
    status,
    activeTab,
    isPending,
    slabsCount,
    totalSlabErrors = 0,
    tSettings,
    onBack,
    onSaveSlabs,
    isSlabsDirty = false,
    isReadOnly = false,
  } = props;

  return (
    <div className="sticky top-12 md:top-16 z-20 bg-background/95 backdrop-blur-sm py-4 border-b border-border flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 transition-all">
      <div className="flex items-center gap-3 min-w-0 flex-1">
        <Button
          variant="ghost"
          size="icon"
          className="rounded-full shrink-0"
          onClick={onBack}
          title={tSettings("rates.btnBack")}
        >
          <ChevronLeft className="size-5" />
        </Button>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2 flex-wrap sm:flex-nowrap">
            <h1
              className="text-xl font-bold tracking-tight text-foreground truncate max-w-xs sm:max-w-md lg:max-w-xl"
              title={
                isCreate ? tSettings("rates.createTitle") : tSettings("rates.editTitle", { code })
              }
            >
              {isCreate ? tSettings("rates.createTitle") : tSettings("rates.editTitle", { code })}
            </h1>
            {!isCreate && <StatusBadge status={status} tSettings={tSettings} />}
          </div>
          <p className="text-xs text-muted-foreground mt-1 truncate">
            {isCreate ? tSettings("rates.createSubtitle") : tSettings("rates.editSubtitle")}
          </p>
        </div>
      </div>

      <div className="flex items-center gap-3 shrink-0">
        {activeTab === "info" && <InfoTabButtons {...props} />}

        {activeTab === "slabs" && !isCreate && !isReadOnly && (
          <Button
            size="sm"
            disabled={isPending || slabsCount === 0 || !isSlabsDirty || totalSlabErrors > 0}
            onClick={onSaveSlabs}
          >
            {isPending ? (
              <Loader2 className="mr-2 size-4 animate-spin" />
            ) : (
              <CheckCircle className="mr-2 size-4" />
            )}
            {tSettings("rates.btnSaveSlabs")}
          </Button>
        )}
      </div>
    </div>
  );
}

function checkSlabsDirty(slabs: SlabItem[], initialSlabs: SlabItem[]): boolean {
  if (slabs.length !== initialSlabs.length) return true;
  return slabs.some((s1, i) => {
    const s2 = initialSlabs[i];
    if (!s2) return true;
    return (
      s1.startWeight !== s2.startWeight ||
      s1.endWeight !== s2.endWeight ||
      s1.rateType !== s2.rateType ||
      s1.amount !== s2.amount
    );
  });
}

function mapAssignedGroups(
  existingRate:
    | { groups?: { customerGroup: { id: number; code: string; name: string } }[] }
    | undefined,
) {
  if (!existingRate?.groups) return [];
  return existingRate.groups.map((g) => ({
    id: g.customerGroup.id,
    code: g.customerGroup.code,
    name: g.customerGroup.name,
  }));
}

function filterCustomerGroups<T extends { id: number; code: string; name: string }>(
  groups: T[] | undefined,
  search: string,
): T[] {
  if (!groups) return [];
  if (!search.trim()) return groups;
  const term = search.toLowerCase().trim();
  return groups.filter(
    (g) => g.code.toLowerCase().includes(term) || g.name.toLowerCase().includes(term),
  );
}

function useRateCardMutations(rateCardId: number | null, tSettings: (key: string) => string) {
  const router = useRouter();
  const t = useToast();
  const utils = trpc.useUtils();

  const createMut = trpc.viewer.rateCards.create.useMutation({
    onSuccess: (card) => {
      t.toast(tSettings("rates.toastCreateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      router.push(`/settings/rates/${card.id}/edit?tab=slabs`);
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const updateMut = trpc.viewer.rateCards.update.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastUpdateSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const submitReviewMut = trpc.viewer.rateCards.submitForReview.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastSubmitSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const approveMut = trpc.viewer.rateCards.approve.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastApproveSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => {
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
      t.toast(formatErrorMessage(err.message), "error");
    },
  });

  const rejectMut = trpc.viewer.rateCards.reject.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastRejectSuccess"), "success");
      utils.viewer.rateCards.list.invalidate();
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => {
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
      t.toast(formatErrorMessage(err.message), "error");
    },
  });

  const importSlabsMut = trpc.viewer.rateCards.importSlabs.useMutation({
    onSuccess: () => {
      t.toast(tSettings("rates.toastImportSuccess"), "success");
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  return {
    createMut,
    updateMut,
    submitReviewMut,
    approveMut,
    rejectMut,
    importSlabsMut,
  };
}

interface AssignGroupsModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  code: string;
  groupSearch: string;
  onGroupSearchChange: (val: string) => void;
  filteredGroups: { id: number; code: string; name: string }[];
  selectedGroupIds: number[];
  onToggleGroup: (id: number) => void;
  isPending: boolean;
  onSave: () => void;
}

function AssignGroupsModal({
  open,
  onOpenChange,
  code,
  groupSearch,
  onGroupSearchChange,
  filteredGroups,
  selectedGroupIds,
  onToggleGroup,
  isPending,
  onSave,
}: AssignGroupsModalProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg sm:max-w-xl overflow-hidden">
        <DialogHeader>
          <DialogTitle className="text-base font-bold break-all pr-6">
            Gán nhóm khách hàng: {code}
          </DialogTitle>
        </DialogHeader>

        <div className="flex flex-col gap-3 py-2">
          <span className="text-xs text-muted-foreground">
            Vui lòng chọn các nhóm khách hàng được áp dụng bảng giá cước tùy chỉnh này:
          </span>

          <Input
            type="text"
            placeholder="Tìm kiếm nhóm khách hàng (mã, tên)..."
            value={groupSearch}
            onChange={(e) => onGroupSearchChange(e.target.value)}
            className="h-9 text-xs"
          />

          <div className="flex flex-col gap-1.5 border border-input rounded-lg p-2 max-h-64 sm:max-h-72 overflow-y-auto bg-muted/10">
            {filteredGroups.length === 0 ? (
              <span className="text-xs text-muted-foreground italic text-center py-6">
                Không tìm thấy nhóm khách hàng nào
              </span>
            ) : (
              filteredGroups.map((group) => {
                const checked = selectedGroupIds.includes(group.id);
                return (
                  <label
                    key={group.id}
                    className="flex items-start gap-2.5 text-xs sm:text-sm cursor-pointer select-none hover:bg-accent/60 p-2 rounded-md transition-colors border border-transparent hover:border-border/60"
                  >
                    <input
                      type="checkbox"
                      checked={checked}
                      onChange={() => onToggleGroup(group.id)}
                      className="mt-0.5 rounded border-input text-primary focus:ring-primary size-4 shrink-0"
                    />
                    <div className="flex flex-col min-w-0 flex-1">
                      <span className="font-medium text-foreground break-all leading-tight">
                        {group.name}
                      </span>
                      <span className="text-[11px] font-mono text-muted-foreground break-all mt-0.5">
                        ({group.code})
                      </span>
                    </div>
                  </label>
                );
              })
            )}
          </div>
        </div>

        <DialogFooter className="flex flex-row items-center justify-between sm:justify-between gap-2 border-t border-border/60 pt-3">
          <span className="text-xs text-muted-foreground">
            Đã chọn:{" "}
            <strong className="font-semibold text-primary">{selectedGroupIds.length}</strong> nhóm
          </span>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              Hủy
            </Button>
            <Button size="sm" disabled={isPending} onClick={onSave}>
              Lưu thay đổi
            </Button>
          </div>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function useAutoSelectFirstSlab(activeTab: string, isReadOnly: boolean, slabsLength: number) {
  useEffect(() => {
    if (activeTab === "slabs" && !isReadOnly && slabsLength > 0) {
      const timer = setTimeout(() => {
        const firstInput = document.getElementById(
          "slab-amount-input-0",
        ) as HTMLInputElement | null;
        if (firstInput) {
          firstInput.focus();
          firstInput.select();
        }
      }, 150);
      return () => clearTimeout(timer);
    }
  }, [activeTab, isReadOnly, slabsLength]);
}

function useRateCardInitEffect(
  isCreate: boolean,
  existingRate: unknown,
  reset: (val: unknown) => void,
  setSlabs: (slabs: SlabItem[]) => void,
  setInitialSlabs: (slabs: SlabItem[]) => void,
) {
  useEffect(() => {
    if (isCreate) {
      reset(INITIAL_FORM_STATE);
      setSlabs([]);
      setInitialSlabs([]);
    } else if (existingRate) {
      reset(mapExistingRateToForm(existingRate as Parameters<typeof mapExistingRateToForm>[0]));
      const slabVal = mapExistingRateToSlabs(
        existingRate as Parameters<typeof mapExistingRateToSlabs>[0],
      );
      setSlabs(slabVal);
      setInitialSlabs(slabVal);
    }
  }, [isCreate, existingRate, reset, setSlabs, setInitialSlabs]);
}

function navigateWithConfirm(
  isDirty: boolean,
  askConfirm: ReturnType<typeof useConfirm>["askConfirm"],
  tSettings: (key: string) => string,
  onNavigate: () => void,
) {
  if (isDirty) {
    askConfirm({
      title: tSettings("rates.confirmBackTitle"),
      message: tSettings("rates.confirmBackMessage"),
      confirmLabel: tSettings("rates.btnLeave"),
      cancelLabel: tSettings("rates.btnStay"),
      confirmColor: "warning",
      onConfirm: onNavigate,
    });
  } else {
    onNavigate();
  }
}

function useRateCardPermissions() {
  const { hasPermission: canCreate } = useRequirePermission([Permissions.RATES_CREATE]);
  const { hasPermission: canUpdate } = useRequirePermission([Permissions.RATES_UPDATE]);
  const { hasPermission: canApprove } = useRequirePermission([Permissions.RATES_APPROVE]);

  return { canCreate, canUpdate, canApprove };
}

function useRateCardActiveTab() {
  const pathname = usePathname();
  const router = useRouter();
  const searchParams = useSearchParams();
  const tabParam = searchParams.get("tab");

  const activeTab = useMemo<"info" | "slabs" | "logs">(() => {
    if (tabParam === "slabs" || tabParam === "logs") return tabParam;
    return "info";
  }, [tabParam]);

  const setActiveTab = useCallback(
    (tab: "info" | "slabs" | "logs") => {
      const params = new URLSearchParams(searchParams.toString());
      params.set("tab", tab);
      const qs = params.toString();
      router.push(`${pathname}${qs ? `?${qs}` : ""}`, { scroll: false });
    },
    [router, pathname, searchParams],
  );

  return { activeTab, setActiveTab };
}

function useRateCardQueries(rateCardId: number | null, isCreate: boolean, activeTab: string) {
  const { data: existingRate, isLoading: loadingDetails } = trpc.viewer.rateCards.get.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null },
  );

  const { data: logs, isLoading: loadingLogs } = trpc.viewer.rateCards.listLogs.useQuery(
    { id: rateCardId ?? 0 },
    { enabled: !isCreate && rateCardId !== null && activeTab === "logs" },
  );

  return { existingRate, loadingDetails, logs, loadingLogs };
}

export function RateCardForm({ rateCardId }: RateCardFormProps) {
  const isCreate = rateCardId === null;
  const router = useRouter();
  const t = useToast();
  const tSettings = useTranslations("settings");
  const utils = trpc.useUtils();
  const { askConfirm, dialogProps: confirmDialogProps } = useConfirm();

  const { canCreate, canUpdate, canApprove } = useRateCardPermissions();
  const { activeTab, setActiveTab } = useRateCardActiveTab();

  const {
    register,
    control,
    handleSubmit,
    reset,
    watch,
    setValue,
    formState: { errors, isDirty: isInfoDirty },
  } = useForm<typeof INITIAL_FORM_STATE>({
    mode: "onChange",
    resolver: zodResolver(rateCardFormSchema),
    defaultValues: INITIAL_FORM_STATE,
  });

  const formData = watch();
  const [slabs, setSlabs] = useState<SlabItem[]>([]);
  const [initialSlabs, setInitialSlabs] = useState<SlabItem[]>([]);
  const isReadOnly = !isCreate
    ? (formData.status !== "DRAFT" && formData.status !== "REJECTED") || !canUpdate
    : !canCreate;

  const { existingRate, loadingDetails, logs, loadingLogs } = useRateCardQueries(
    rateCardId,
    isCreate,
    activeTab,
  );

  useRateCardInitEffect(isCreate, existingRate, reset, setSlabs, setInitialSlabs);
  useAutoSelectFirstSlab(activeTab, isReadOnly, slabs.length);

  const isSlabsDirty = useMemo(() => checkSlabsDirty(slabs, initialSlabs), [slabs, initialSlabs]);

  const { createMut, updateMut, submitReviewMut, approveMut, rejectMut, importSlabsMut } =
    useRateCardMutations(rateCardId, tSettings);

  const handleSaveInfo = handleSubmit(
    (values) => {
      const payload = prepareSavePayload(values);
      if (isCreate) {
        createMut.mutate(payload);
      } else if (rateCardId) {
        updateMut.mutate({ id: rateCardId, ...payload });
      }
    },
    () => {
      t.toast(tSettings("rates.toastValidationError"), "error");
    },
  );

  const handleSubmitReview = () => {
    if (!rateCardId) return;
    submitReviewMut.mutate({ id: rateCardId });
  };

  const handleApprove = () => {
    if (!rateCardId) return;
    approveMut.mutate({ id: rateCardId });
  };

  const handleReject = () => {
    if (!rateCardId) return;
    rejectMut.mutate({ id: rateCardId });
  };

  const handleSaveSlabs = () => {
    if (!rateCardId) return;
    importSlabsMut.mutate({
      rateCardId,
      slabs,
    });
  };

  const handleBack = useCallback(() => {
    navigateWithConfirm(isInfoDirty || isSlabsDirty, askConfirm, tSettings, () =>
      router.push("/settings/rates"),
    );
  }, [isInfoDirty, isSlabsDirty, askConfirm, router, tSettings]);

  const assignedGroups = useMemo(() => mapAssignedGroups(existingRate), [existingRate]);

  const hasAssignedGroups = formData.type === "CUSTOM" ? assignedGroups.length > 0 : true;

  const [assignGroupModalOpen, setAssignGroupModalOpen] = useState(false);
  const [selectedGroupIds, setSelectedGroupIds] = useState<number[]>([]);
  const [groupSearch, setGroupSearch] = useState("");

  const { data: allGroups } = trpc.viewer.customerGroups.listAll.useQuery(undefined, {
    enabled: formData.type === "CUSTOM" && assignGroupModalOpen,
    staleTime: 5 * 60 * 1000,
  });

  const filteredGroups = useMemo(
    () => filterCustomerGroups(allGroups, groupSearch),
    [allGroups, groupSearch],
  );

  const assignGroupsMut = trpc.viewer.rateCards.assignGroups.useMutation({
    onSuccess: () => {
      t.toast("Đã cập nhật nhóm khách hàng thành công.", "success");
      setAssignGroupModalOpen(false);
      utils.viewer.rateCards.get.invalidate({ id: rateCardId ?? 0 });
      utils.viewer.rateCards.list.invalidate();
    },
    onError: (err) => t.toast(formatErrorMessage(err.message), "error"),
  });

  const handleOpenAssignGroups = useCallback(() => {
    setSelectedGroupIds(assignedGroups.map((g) => g.id));
    setGroupSearch("");
    setAssignGroupModalOpen(true);
  }, [assignedGroups]);

  const totalSlabErrors = useMemo(() => {
    return countSlabErrors(slabs, formData, tSettings);
  }, [slabs, formData, tSettings]);

  const isPending =
    createMut.isPending ||
    updateMut.isPending ||
    submitReviewMut.isPending ||
    approveMut.isPending ||
    rejectMut.isPending ||
    importSlabsMut.isPending ||
    assignGroupsMut.isPending;

  if (loadingDetails) {
    return (
      <div className="flex min-h-[400px] items-center justify-center">
        <Loader2 className="size-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-6 w-full">
      <FormHeader
        isCreate={isCreate}
        code={formData.code}
        status={formData.status}
        activeTab={activeTab}
        isPending={isPending}
        slabsCount={slabs.length}
        totalSlabErrors={totalSlabErrors}
        hasAssignedGroups={hasAssignedGroups}
        tSettings={tSettings}
        onBack={handleBack}
        onSaveInfo={handleSaveInfo}
        onSubmitReview={handleSubmitReview}
        onApprove={handleApprove}
        onReject={handleReject}
        onSaveSlabs={handleSaveSlabs}
        isInfoDirty={isInfoDirty}
        isSlabsDirty={isSlabsDirty}
        isReadOnly={isReadOnly}
        canCreate={canCreate}
        canUpdate={canUpdate}
        canApprove={canApprove}
      />

      <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "info" | "slabs" | "logs")}>
        <Card className="rounded-lg border border-border bg-card overflow-hidden">
          {!isCreate && (
            <div className="px-6 pt-6 pb-2 flex items-center">
              <TabsList className="inline-flex h-10 items-center justify-start rounded-lg bg-muted p-1 border border-border">
                <TabsTrigger
                  value="info"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Info size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabGeneral")}</span>
                </TabsTrigger>
                <TabsTrigger
                  value="slabs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <Scale size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabSlabs")}</span>
                  {totalSlabErrors > 0 && (
                    <Badge
                      variant="destructive"
                      className="ml-1 px-1.5 py-0 text-[10px] h-4 leading-none font-semibold"
                    >
                      {totalSlabErrors}
                    </Badge>
                  )}
                </TabsTrigger>
                <TabsTrigger
                  value="logs"
                  className="flex items-center gap-1.5 rounded-md px-4 py-1.5 text-xs md:text-sm font-medium text-muted-foreground transition-all hover:bg-background/50 hover:text-foreground data-[state=active]:bg-background data-[state=active]:text-foreground data-[state=active]:shadow-sm"
                >
                  <History size={16} className="shrink-0" />
                  <span>{tSettings("rates.tabLogs")}</span>
                </TabsTrigger>
              </TabsList>
            </div>
          )}

          <CardContent className="px-6 pb-6 pt-6">
            <TabsContent value="info" className="mt-0 outline-none">
              <GeneralInfoTab
                control={control}
                register={register}
                errors={errors}
                watch={watch}
                setValue={setValue}
                isCreate={isCreate}
                tSettings={tSettings}
                status={formData.status}
                rateCardId={rateCardId}
                assignedGroups={assignedGroups}
                onOpenAssignGroups={handleOpenAssignGroups}
              />
            </TabsContent>

            {!isCreate && (
              <>
                <TabsContent value="slabs" className="mt-0 outline-none">
                  <SlabsTab
                    formData={formData}
                    slabs={slabs}
                    setSlabs={setSlabs}
                    tSettings={tSettings}
                    isReadOnly={isReadOnly}
                    askConfirm={askConfirm}
                  />
                </TabsContent>

                <TabsContent value="logs" className="mt-0 outline-none">
                  <LogsTab logs={logs} loadingLogs={loadingLogs} tSettings={tSettings} />
                </TabsContent>
              </>
            )}
          </CardContent>
        </Card>
      </Tabs>

      {/* Assign Groups Modal */}
      {assignGroupModalOpen && (
        <AssignGroupsModal
          open={assignGroupModalOpen}
          onOpenChange={setAssignGroupModalOpen}
          code={formData.code}
          groupSearch={groupSearch}
          onGroupSearchChange={setGroupSearch}
          filteredGroups={filteredGroups}
          selectedGroupIds={selectedGroupIds}
          onToggleGroup={(id) => {
            setSelectedGroupIds((prev) =>
              prev.includes(id) ? prev.filter((groupId) => groupId !== id) : [...prev, id],
            );
          }}
          isPending={assignGroupsMut.isPending || !rateCardId}
          onSave={() => {
            if (rateCardId) {
              assignGroupsMut.mutate({
                id: rateCardId,
                customerGroupIds: selectedGroupIds,
              });
            }
          }}
        />
      )}

      <ConfirmDialog {...confirmDialogProps} />
    </div>
  );
}
